- name: Install nodejs
  pkgng: name={{item}}
  with_items:
  - node
  - npm

- name: Download kibana
  get_url: url=https://github.com/elastic/kibana/archive/v4.4.2.tar.gz dest={{ logstash_directory }}/kibana.tar.gz

- name: Remove old install
  file: state=absent dest={{ logstash_directory }}/kibana

- name: Unarchive kibana
  unarchive: src={{ logstash_directory }}/kibana.tar.gz copy=no dest={{ logstash_directory }}

- name: Move archive
  command: mv {{ logstash_directory }}/kibana-4.4.2 {{ logstash_directory }}/kibana

- name: Remove archive
  file: state=absent dest={{ logstash_directory }}/kibana.tar.gz

- name: Install npm modules
  command: npm install
  args:
    chdir: "{{ logstash_directory }}/kibana"

- name: Mark as installed
  file: state=touch dest={{ logstash_directory }}/kibana/.ansible-installed

- name: Create service dir
  file: path=/var/service/kibana state=directory

- name: Copy service file
  copy: src=service/kibana.run dest=/var/service/kibana/run mode=0700
